export PS1="\w >"
HISTCONTROL=ignoredups
alias norma="clear && norminette -RCheckForbiddenSourceHeader"
alias gccm="gcc -Wall -Wextra -Werror"
alias removedotgit="mv .gitignore gitignore && rm -fr .git"
alias removecachegit="git rm -r --cached ."

#source ~/.bashrc
#find \. -type f -name '*.c' \! -name 'main.c'