export PS1="\w >"
HISTCONTROL=ignoredups
alias norma="clear && norminette -R CheckForbiddenSourceHeader ex* ../ex*"
alias gccm="clear && gcc -Wall -Wextra -Werror main.c"
alias removedotgit="mv .gitignore gitignore && rm -fr .git"
alias removecachegit="git rm -r --cached ."

#source ~/.bashrc
#find \. -type f -name '*.c' \! -name 'main.c'